var emojis = {
  '[微笑]': '[weixiao]',
  '[撇嘴]': '[piezui]',
  '[色]': '[se]',
  '[发呆]': '[fadai]',
  '[酷]': '[cool]',
  '[大哭]': '[daku]',
  '[害羞]': '[haixiu]',
  '[闭嘴]': '[bizui]',

  '[睡觉]': '[shuijiao]',
  '[哭]': '[ku]',
  '[尴尬]': '[ganga]',
  '[发怒]': '[fanu]',
  '[眨眼]': '[zhayan]',
  '[龇牙]': '[ziya]',
  '[惊讶]': '[jingya]',
  '[难过]': '[nanguo]',

  '[得意]': '[deyi]',
  '[囧]': '[jiong]',
  '[抓狂]': '[zhuakuang]',
  '[呕吐]': '[outu]',
  '[偷笑]': '[touxiao]',
  '[开心]': '[kaixin]',
  '[白眼]': '[baiyan]',

  '[傲慢]': '[aoman]',
  '[饥饿]': '[jie]',
  '[困]': '[kun]',
  '[惊吓]': '[jingxia]',
  '[流汗]': '[liuhan]',
  '[大笑]': '[daxiao]',
  '[抽烟]': '[chouyan]',
  '[奋斗]': '[fendou]',

  '[骂人]': '[maren]',
  '[问]': '[wen]',
  '[嘘]': '[xu]',
  '[晕]': '[yun]',
  '[狂燥]': '[kuangzao]',
  '[衰]': '[shuai]',
  '[骷髅]': '[kulou]',
  '[敲头]': '[qiaotou]',

  '[拜拜]': '[baibai]',
  '[擦汗]': '[cahan]',
  '[挖鼻孔]': '[wabikong]',
  '[恭喜]': '[gongxi]',
  '[糗]': '[qiu]',
  '[坏笑]': '[huaixiao]',
  '[左哼哼]': '[zuohengheng]',

  '[右哼哼]': '[youhengheng]',
  '[打哈欠]': '[dahaqian]',
  '[鄙视]': '[bishi]',
  '[受委屈]': '[shouweiqu]',
  '[委屈]': '[weiqu]',
  '[奸笑]': '[jianxiao]',
  '[亲亲]': '[qingqing]',
  '[吓]': '[xia]',

  '[可怜]': '[kelian]',
  '[菜刀]': '[caidao]',
  '[西瓜]': '[xigua]',
  '[啤酒]': '[pijiu]',
  '[篮球]': '[lanqiu]',
  '[乒乓球]': '[pingpangqiu]',
  '[咖啡]': '[kafei]',
  '[米饭]': '[mifan]',

  '[猪头]': '[zhutou]',
  '[玫瑰]': '[meigui]',
  '[花谢了]': '[huaxiele]',
  '[红唇]': '[hongchun]',
  '[心]': '[xin]',
  '[心碎]': '[xinsui]',
  '[蛋糕]': '[dangao]',

  '[闪电]': '[shandian]',
  '[炸弹]': '[zhadan]',
  '[刀]': '[dao]',
  '[足球]': '[zuqiu]',
  '[瓢虫]': '[piaochong]',
  '[大便]': '[dabian]',
  '[夜晚]': '[yewan]',
  '[太阳]': '[taiyang]',

  '[礼物]': '[liwu]',
  '[抱抱]': '[baobao]',
  '[强]': '[qiang]',
  '[弱]': '[ruo]',
  '[握手]': '[woshou]',
  '[Yeah]': '[yeah]',
  '[抱拳]': '[baoquan]',
  '[来]': '[lai]',

  '[加油]': '[jiayou]',
  '[差劲]': '[chajin]',
  '[我爱你]': '[iloveyou]',
  '[No]': '[no]',
  '[Ok]': '[ok]'
}

export default emojis
